name: Download Files by URL

on:
  workflow_dispatch:
    inputs:
      url_list:
        description: 'Comma-separated list of URLs to download files from'
        required: true
      file_types:
        description: 'Comma-separated list of file extensions to download (e.g., pdf, jpg)'
        required: true

jobs:
  download_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download Files
        run: |
          # Install necessary Python package
          pip install requests

          # Import modules
          import os
          import requests

          # Read input values
          url_list = '${{ github.event.inputs.url_list }}'.split(',')
          file_types = [f".{ext.strip()}" for ext in '${{ github.event.inputs.file_types }}'.split(',')]
          download_path = "./downloaded_files"

          # Create a directory to store downloaded files
          os.makedirs(download_path, exist_ok=True)

          # Function to download files
          def download_file(url, download_path):
              try:
                  response = requests.get(url, stream=True)
                  if response.status_code == 200:
                      filename = url.split('/')[-1]
                      file_ext = os.path.splitext(filename)[1].lower()
                      if file_ext in file_types:
                          with open(os.path.join(download_path, filename), 'wb') as f:
                              f.write(response.content)
                          print(f"Downloaded {filename}")
                      else:
                          print(f"Skipped {filename} (extension not in {file_types})")
                  else:
                      print(f"Failed to download {url} (Status: {response.status_code})")
              except Exception as e:
                  print(f"Error downloading {url}: {e}")

          # Download each file from the URL list
          for url in url_list:
              download_file(url.strip(), download_path)

      - name: Commit and Push Downloads
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add downloaded_files/*
          git commit -m "Add downloaded files"
          git push
